### ISSUE TITLE
Include widget in widget

### ISSUE THREAD

**Issue by jacobdubail** [apostrophecms-legacy/apostrophe-schema-widgets#3]
Is it possible to include a widget in another widget?

If I define some kind of 'text-button' widget, I'd like to use that widget inside of another widget like 'banner'. I'd define it in the schema, ideally.

Did that make any sense?

**Comment by boutell** [comment]
Yes schemas support widgets, see the "singleton" field type.

On Wed, Dec 9, 2015 at 6:47 PM, Jacob Dubail <notifications@github.com>
wrote:

> Is it possible to include a widget in another widget?
>
> If I define some kind of 'text-button' widget, I'd like to use that widget
> inside of another widget like 'banner'. I'd define it in the schema,
> ideally.
>
> Did that make any sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/apostrophe-schema-widgets/issues/3>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
