### ISSUE TITLE
Add rows to a table

### ISSUE THREAD

**Issue by spacecowboyian** [apostrophecms-legacy/apostrophe-schema-widgets#5]
I'd like to create a widget that allows me to insert new rows into a table. I've got the aposArea sitting in a `<tbody>` and it will render a new `<tr>` from my template inside that `<tbody>` however the add content area ends up getting spit out of the table by the browser because its wrapped in a `<div>`

**Page Template:**

`<table class="table style-list">
                    <thead>
                        <tr>
                            <th>Team</th>
                            <th>Name</th>
                            <th>Release</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{ aposArea(page, 'analytics', {
                            richText: false,
                            controls: ['prototype']
                        }) }}
                    </tbody>
                </table>`

**Row Template:**

`<tr>
    <td>
        {{item.team}}
    </td>
    <td>
        {{item.name}}
    </td>
    <td>
        {{item.release}}
    </td>
    <td>
        {{item.status}}
    </td>
</tr>`

**End result:**
<img width="863" alt="screen shot 2016-06-15 at 3 23 19 pm" src="https://cloud.githubusercontent.com/assets/77822/16096103/20f0f882-330d-11e6-9bee-ddbc860a79fb.png">

Just wondering if there is documentation somewhere that talks about adding rows to tables.

**Comment by boutell** [comment]
This is not something widgets are designed to do, they are designed to have
a wrapper div.

However, you can make a *single* widget that contains an "array" field with
its own schema that has the fields for a row, and then your .html would
output the entire table. Very simple and powerful. Check out the docs on
those.

On Wed, Jun 15, 2016 at 4:27 PM, Ian Jennings <notifications@github.com>
wrote:

> I'd like to create a widget that allows me to insert new rows into a
> table. I've got the aposArea sitting in a <tbody> and it will render a
> new <tr> from my template inside that <tbody> however the add content
> area ends up getting spit out of the table by the browser because its
> wrapped in a <div>
>
> *Page Template:*
>
> <table class="table style-list">
> <thead>
> <tr>
> <th>Team</th>
> <th>Name</th>
> <th>Release</th>
> <th>Status</th>
> </tr>
> </thead>
> <tbody>
> {{ aposArea(page, 'analytics', {
> richText: false,
> controls: ['prototype']
> }) }}
> </tbody>
> </table>
>
> *Row Template:*
>
> <tr>
> <td>
> {{item.team}}
> </td>
> <td>
> {{item.name}}
> </td>
> <td>
> {{item.release}}
> </td>
> <td>
> {{item.status}}
> </td>
> </tr>
>
> *End result:*
> [image: screen shot 2016-06-15 at 3 23 19 pm]
> <https://cloud.githubusercontent.com/assets/77822/16096103/20f0f882-330d-11e6-9bee-ddbc860a79fb.png>
>
> Just wondering if there is documentation somewhere that talks about adding
> rows to tables.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/apostrophe-schema-widgets/issues/5>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAB9fSRn1-V8nk5oWrDDu807aG-jrE_1ks5qMGBGgaJpZM4I2wop>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by spacecowboyian** [comment]
Yup. I think I've moved on to using child pages for this. Thanks!
